-- LinkDub worker queue, progress, result, and editable segment contract.

alter table public.linkdub_jobs
  add column if not exists priority smallint not null default 0,
  add column if not exists attempts integer not null default 0,
  add column if not exists max_attempts integer not null default 3,
  add column if not exists worker_id text,
  add column if not exists claimed_at timestamptz,
  add column if not exists heartbeat_at timestamptz,
  add column if not exists finished_at timestamptz,
  add column if not exists duration_seconds numeric,
  add column if not exists output_path text,
  add column if not exists translated_subtitles_url text,
  add column if not exists translated_subtitles_path text,
  add column if not exists source_subtitles_url text,
  add column if not exists source_subtitles_path text,
  add column if not exists processing_options jsonb not null default '{}'::jsonb;

create index if not exists linkdub_jobs_claim_idx
  on public.linkdub_jobs (priority desc, created_at)
  where status = 'queued';

create table if not exists public.linkdub_segments (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.linkdub_jobs(id) on delete cascade,
  segment_index integer not null,
  start_seconds numeric not null check (start_seconds >= 0),
  end_seconds numeric not null check (end_seconds > start_seconds),
  source_text text not null default '',
  translated_text text not null default '',
  voice_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (job_id, segment_index)
);

alter table public.linkdub_segments enable row level security;

drop policy if exists linkdub_public_read_segments on public.linkdub_segments;
create policy linkdub_public_read_segments
  on public.linkdub_segments
  for select
  to anon, authenticated
  using (true);

grant select on public.linkdub_segments to anon, authenticated;
grant select, insert, update, delete on public.linkdub_segments to service_role;
grant usage, select on sequence public.linkdub_segments_id_seq to service_role;

-- Keep the existing unauthenticated prototype compatible while preventing a
-- browser from creating a fake completed job.
drop policy if exists linkdub_public_create_jobs on public.linkdub_jobs;
create policy linkdub_public_create_jobs
  on public.linkdub_jobs
  for insert
  to anon, authenticated
  with check (
    status = 'queued'
    and progress = 0
    and worker_id is null
    and output_url is null
    and error is null
  );

grant select, insert on public.linkdub_jobs to anon, authenticated;
revoke update, delete on public.linkdub_jobs from anon, authenticated;
grant select, insert, update, delete on public.linkdub_jobs to service_role;

create or replace function public.linkdub_set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists linkdub_jobs_set_updated_at on public.linkdub_jobs;
create trigger linkdub_jobs_set_updated_at
before update on public.linkdub_jobs
for each row execute function public.linkdub_set_updated_at();

drop trigger if exists linkdub_segments_set_updated_at on public.linkdub_segments;
create trigger linkdub_segments_set_updated_at
before update on public.linkdub_segments
for each row execute function public.linkdub_set_updated_at();

-- Only the Supabase service role used by the OIDC-authenticated Edge Function
-- can atomically claim work. SKIP LOCKED prevents duplicate processing.
create or replace function public.claim_linkdub_job(p_worker_id text)
returns setof public.linkdub_jobs
language plpgsql
security definer
set search_path = ''
as $$
begin
  return query
  with candidate as (
    select j.id
    from public.linkdub_jobs as j
    where j.attempts < j.max_attempts
      and (
        j.status = 'queued'
        or (
          j.status = 'processing'
          and coalesce(j.heartbeat_at, j.claimed_at, j.updated_at) < now() - interval '90 minutes'
        )
      )
    order by j.priority desc, j.created_at
    for update skip locked
    limit 1
  )
  update public.linkdub_jobs as j
  set status = 'processing',
      stage = 'Downloading',
      progress = 1,
      worker_id = p_worker_id,
      attempts = j.attempts + 1,
      claimed_at = now(),
      heartbeat_at = now(),
      finished_at = null,
      error = null
  from candidate
  where j.id = candidate.id
  returning j.*;
end;
$$;

revoke all on function public.claim_linkdub_job(text) from public, anon, authenticated;
grant execute on function public.claim_linkdub_job(text) to service_role;

-- Result assets are public because the current LinkDub prototype has no user
-- accounts yet. Uploads remain private to the worker through signed upload URLs.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'linkdub-results',
  'linkdub-results',
  true,
  2147483648,
  array['video/mp4', 'application/x-subrip', 'text/plain', 'audio/mpeg', 'audio/wav']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists linkdub_public_read_results on storage.objects;
create policy linkdub_public_read_results
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'linkdub-results');

-- Publish real status changes to Supabase Realtime for future clients. The
-- frontend also polls, so it still works if a websocket is unavailable.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'linkdub_jobs'
  ) then
    alter publication supabase_realtime add table public.linkdub_jobs;
  end if;
end
$$;

